1:   Test case #4
2:   Testing: select with const
3:   Testing: const ChessBoardArray a5(5, 7)
4:   Testing: cout << a5.select(7, 7) << endl
5:   0
6:   Testing: cout << a5.select(11, 11) << endl
7:   0
8:   Testing: cout << a5
9:      0   0   0   0   0
10:      0   0   0   0   0
11:      0   0   0   0   0
12:      0   0   0   0   0
13:      0   0   0   0   0
14:   Testing: a5.select(12, 6)
15:   out_of_range exception is thrown
16:   Testing: a5.select(5, 6)
17:   out_of_range exception is thrown
18:   Testing: a5.select(0, 0)
19:   out_of_range exception is thrown
